# This is a basic workflow to help you get started with Actions

name: Build and deploy blog site

defaults:
  run:
    shell: bash  

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  HUGO_VERSION: 0.71.1
  SITE_BASEURL: https://blog.ckhill.com
  AZURE_STORAGE_ACCOUNT: blogckhillcom
  # AZURE_STORAGE_KEY: <Stored as Repository Secret>
  
jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    # Checkout latest codebase from repository
      - name: Checkout blog repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          clean: true
          submodules: false
    # Download Hugo
      - name: Download Hugo v${{ env.HUGO_VERSION }} Linux x64
        run: "wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb -O hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb"
    # Install Hugo
      - name: Install Hugo
        run: sudo dpkg -i hugo*.deb
    # Build site
      - name: Build site with Hugo
        run: hugo --baseUrl '${{ env.SITE_BASEURL }}'
    # Deploy site via Hugo
      - name: Deploy build to static site (Azure blob)
        run: hugo deploy --maxDeletes -1
        env:
          AZURE_STORAGE_ACCOUNT: ${{ env.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
