# This is a basic workflow to help you get started with Actions

name: Build and deploy blog site

defaults:
  run:
    shell: bash  

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  HUGO_VERSION: 0.68.3
  SITE_BASEURL: https://blog.ckhill.com
  AZURE_STORAGE_ACCOUNT: blogckhillcom
  # AZURE_STORAGE_KEY: <Stored as Repository Secret>
  
jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    # Checkout latest codebase from repository
      - name: Checkout blog repository code
        uses: actions/checkout@v2

    # Download and Install Hugo
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "${{ env.HUGO_VERSION }}"
    
    # Build site
      - name: Build site with Hugo
        run: hugo --minify
    
    # Deploy site via Hugo
      - name: Deploy build to static site (Azure blob)
        run: hugo deploy --maxDeletes -1
        env:
          AZURE_STORAGE_ACCOUNT: ${{ env.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

    # Invalidate CDN
      - name: Azure service principal login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CDN_APP_CREDENTIALS }}

      - name: Purge CDN
        run:
          az cdn endpoint purge -n ckhillblog.azureedge.net --profile-name ckhillblog --content-paths "/*" --resource-group ckhill-site --no-wait
        
      - name: Azure service principal logout
        run: |
          az logout